package com.example;

import java.net.http.*;
import java.util.ArrayList;
import java.net.URI;

import org.json.*;

import com.example.Textbook;
//import java.time.Duration;
//import java.io.IOException;

public class Thrift_scraper {

    private static final HttpClient client = HttpClient.newHttpClient();
    

    /**
     * basically takes an isbn and attaches it to the thriftbooks search url and sends it as a request,
     * thriftbooks returns a html/javadocs file which is then cut down into a usuable url.
     * @param isbn the isbn of the wanted book
     * @return the exact url for the isbn/book listing on thriftbooks
     * @throws Exception
     */
    private static String generate_url(String isbn) throws Exception{


        HttpRequest isbn_Request = HttpRequest.newBuilder()
            .uri(URI.create("https://www.thriftbooks.com/browse/?b.search=%s".formatted(isbn)))
            //.header("Content-Type","application/json")
            .GET()
            .header("User-Agent","Mozilla/5.0")
            //.POST(HttpRequest.BodyPublishers.ofString(search_query))
            .build();

        HttpResponse<String> isbn_Response = client.send(isbn_Request, HttpResponse.BodyHandlers.ofString());

        int start = isbn_Response.body().indexOf("href=\"")+6;
        int end = isbn_Response.body().indexOf("\"", start);

        String rec_url = "https://www.thriftbooks.com"+isbn_Response.body().substring(start, end);

        return rec_url;

    }

    /**
     * takes the generated url and cuts out the workid from the url using string methods
     * @param rec_url the url generated by searching isbn on thriftbooks
     * @return id, specifcally the workid used by thriftbooks to id their listings
     * needed to fetch the related json
     */
    private static String generate_id(String rec_url){
        int first = rec_url.indexOf('/',rec_url.indexOf("/w/")+3);
        int following = rec_url.indexOf('/',first + 1);
        if(following == -1){
            following = rec_url.length();
        }
        return rec_url.substring(first + 1, following);
    }

    /**
     * uses workid to fetch the correct workinfo json from Thriftbooks, this
     * json contains things like title, authors, price etc
     * @param id the workid, needed to access workinfo json
     * @return a httpRespone<string>, basically the retrieved json in string format
     * @throws Exception
     */
    private static HttpResponse<String> generate_json(String id) throws Exception{

        String info_json = "{\"workId\":%s}".formatted(id);

        HttpRequest info_Request = HttpRequest.newBuilder()
            .uri(URI.create("https://www.thriftbooks.com/stateless/editions/workinfo"))
            .header("Content-Type", "application/json")
            .header("User-Agent", "Mozilla/5.0")
            .POST(HttpRequest.BodyPublishers.ofString(info_json))
            .build();

        HttpResponse<String> info_response = client.send(info_Request, HttpResponse.BodyHandlers.ofString());
        return info_response;
    }

    /**
     * Takes the httpResponse string and turns it into a JSONObject so info can be parsed using org.json
     * parses the required info to create a textbook entry
     * @param isbn the original ISBN given
     * @param url the url to the listing on Thriftbooks website
     * @param info the json formated as a HttpResponse<string>, will be used to extract title, authors, price etc
     * @return a new textbook entry ready to be added to the SearchResults
     */
    private static Textbook generate_Entry(String isbn, String url, HttpResponse<String> info){

        JSONObject workInfoJson = new JSONObject(info.body());
        JSONObject work = workInfoJson.getJSONObject("Work");
        JSONObject active = work.getJSONObject("ActiveEdition");

        // TITLE
        String title = work.getString("Title");

        // AUTHORS
        JSONArray authorsArray = work.getJSONArray("Authors");
        ArrayList<String> authors = new ArrayList<>();

        int x = authorsArray.length();
        for(int y = 0; y<x; y++){
            authors.add(authorsArray.getJSONObject(y).getString("AuthorName"));
        }

        // LOWEST PRICE
        double lowestPrice = active.getDouble("LowPrice");
        // CONDITION
        String condition = active.getString("BuyNowCondition");
        // PUBLISHER
        String publisher = active.getString("Publisher");

        //need to update textbook class with additional variables!
        Textbook new_entry = new Textbook(isbn, lowestPrice, condition, title, authors, publisher, url);
        return new_entry;
    }

    /**
     * This is the main function, it chains all the previous methods together to generate a textbook entry
     * from a given isbn
     * @param given_isbn A standard isbn, unknown what happens if something other then a valid isbn is given
     * @return a textbook object
     */
    public static Textbook scrape_Thriftbooks(String given_isbn){
        try{
            String url = generate_url(given_isbn);
            String workid = generate_id(url);
            HttpResponse<String> json = generate_json(workid);
            return generate_Entry(given_isbn, url, json);
        }catch (Exception e){
            System.err.println("Something failed, improve error message later");
            return null;
        }
    }

    //Main method for testing purposes only
    
    public static void main(String[] args) throws Exception {
        String test_url = generate_url("0471819956");
        System.out.println(test_url);
        String test_id = generate_id(test_url);
        System.out.println(test_id);
        HttpResponse<String> json = generate_json(test_id);
        generate_Entry("0471819956", test_url, json);

    }
}
