package com.masonsaver;

import java.net.http.*;
import java.util.ArrayList;
import java.net.URI;
import org.json.*;

/**
 * ThriftScraper
 *
 * Scrapes textbook listings from ThriftBooks by ISBN.
 *
 * The scraping process happens in four steps:
 *   1. generate_url()    — search ThriftBooks for the ISBN and find the listing URL
 *   2. generate_id()     — extract the internal workId from that URL
 *   3. generate_json()   — fetch the work info JSON using the workId
 *   4. generate_Entry()  — parse the JSON into a ThriftTextbook object
 *
 * scrape_Thriftbooks() chains all four steps together as the main entry point.
 *
 * generate_id() and generate_Entry() are declared public (rather than
 * package-private) so they can be exercised directly from integration
 * and system test classes that live in subpackages (com.masonsaver.integration,
 * com.masonsaver.system), in addition to unit tests in com.masonsaver itself.
 */
public class ThriftScraper {

    private static final HttpClient client = HttpClient.newHttpClient();

    /**
     * Searches ThriftBooks for the given ISBN and returns the matching
     * listing URL by parsing the search results page.
     *
     * @param isbn the ISBN of the wanted book
     * @return the exact URL for the ISBN's book listing on ThriftBooks
     * @throws Exception if the HTTP request fails
     */
    static String generate_url(String isbn) throws Exception {

        HttpRequest isbn_Request = HttpRequest.newBuilder()
                .uri(URI.create("https://www.thriftbooks.com/browse/?b.search=%s".formatted(isbn)))
                .GET()
                .header("User-Agent", "Mozilla/5.0")
                .build();

        HttpResponse<String> isbn_Response = client.send(isbn_Request, HttpResponse.BodyHandlers.ofString());

        int start = isbn_Response.body().indexOf("href=\"") + 6;
        int end = isbn_Response.body().indexOf("\"", start);

        return "https://www.thriftbooks.com" + isbn_Response.body().substring(start, end);
    }

    /**
     * Extracts the internal ThriftBooks workId from a listing URL using
     * pure string parsing. No network access is required.
     *
     * @param rec_url the URL generated by searching the ISBN on ThriftBooks
     * @return the workId used by ThriftBooks to identify listings, needed
     *         to fetch the related JSON work info
     */
    public static String generate_id(String rec_url) {
        int first = rec_url.indexOf('/', rec_url.indexOf("/w/") + 3);
        int following = rec_url.indexOf('/', first + 1);
        if (following == -1) {
            following = rec_url.length();
        }
        return rec_url.substring(first + 1, following);
    }

    /**
     * Uses the workId to fetch the work info JSON from ThriftBooks,
     * which contains title, authors, price, condition, and publisher.
     *
     * @param id the workId needed to access the work info JSON
     * @return the retrieved JSON as an HttpResponse string
     * @throws Exception if the HTTP request fails
     */
    static HttpResponse<String> generate_json(String id) throws Exception {

        String info_json = "{\"workId\":%s}".formatted(id);

        HttpRequest info_Request = HttpRequest.newBuilder()
                .uri(URI.create("https://www.thriftbooks.com/stateless/editions/workinfo"))
                .header("Content-Type", "application/json")
                .header("User-Agent", "Mozilla/5.0")
                .POST(HttpRequest.BodyPublishers.ofString(info_json))
                .build();

        return client.send(info_Request, HttpResponse.BodyHandlers.ofString());
    }

    /**
     * Parses the work info JSON response into a ThriftTextbook object.
     *
     * This method does not make any network calls itself — it only parses
     * the JSON string already contained in the provided HttpResponse,
     * making it fully testable with hardcoded mock responses.
     *
     * @param isbn the original ISBN given
     * @param url  the URL to the listing on the ThriftBooks website
     * @param info the JSON formatted as an HttpResponse string, used to
     *             extract title, authors, price, condition, and publisher
     * @return a new ThriftTextbook entry built from the parsed JSON
     */
    public static ThriftTextbook generate_Entry(String isbn, String url, HttpResponse<String> info) {

        JSONObject workInfoJson = new JSONObject(info.body());
        JSONObject work = workInfoJson.getJSONObject("Work");
        JSONObject active = work.getJSONObject("ActiveEdition");

        String title = work.getString("Title");

        JSONArray authorsArray = work.getJSONArray("Authors");
        ArrayList<String> authors = new ArrayList<>();
        int x = authorsArray.length();
        for (int y = 0; y < x; y++) {
            authors.add(authorsArray.getJSONObject(y).getString("AuthorName"));
        }

        double lowestPrice = active.getDouble("LowPrice");
        String condition = active.getString("BuyNowCondition");
        String publisher = active.getString("Publisher");

        return new ThriftTextbook(isbn, lowestPrice, condition, title, authors, publisher, url);
    }

    /**
     * Main entry point that chains all scraping steps together to produce
     * a complete ThriftTextbook from a given ISBN.
     *
     * If any step fails (network error, malformed response, etc.) this
     * method catches the exception and returns null rather than propagating
     * the error, allowing calling code to handle missing data gracefully.
     *
     * @param given_isbn a standard ISBN string
     * @return a ThriftTextbook object, or null if scraping fails at any step
     */
    public static ThriftTextbook scrape_Thriftbooks(String given_isbn) {
        try {
            String url = generate_url(given_isbn);
            String workid = generate_id(url);
            HttpResponse<String> json = generate_json(workid);
            return generate_Entry(given_isbn, url, json);
        } catch (Exception e) {
            System.err.println("Something failed, improve error message later");
            return null;
        }
    }
}